version: "3.9"

services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"
      - "3001:3000"
    volumes:
      - ./:/data/
    stdin_open: true
    tty: true

  code-graph:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - falkordb
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SECRET_TOKEN=${SECRET_TOKEN:-}
      - CODE_GRAPH_PUBLIC=1